"""
CIDADE A (7 LAGOAS) E CIDADE B(OSWALDO CRUZ)
INDICE DE CRESCIMENTO G1 E G2
"""

def calculo_anos(PA, PB, G1, G2):

 """
FÇÃO QUE CALCULA QTOS ANOS A POP. A LEVA PARA ULTRAPASSAR B, E SE
ULTRAPASSAR 100 ANOS "MAIS DE 1 SÉCULO"

"""
anos = 0
